### ISSUE TITLE
Validation failure on install

### ISSUE THREAD

**Issue by landaro** [2m/coursier-pkgbuild#4]
I currently have the `1.1.0_M4-1` version on my arch system. When I try to upgrade to `1.1.0_M7-1`, the upgrade fails with a validation error.

I run the update with `aurman -Syu` and obtain the following output:
```
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do

~~ initializing aurman...
:: Ignoring installed package kubernetes-helm
~~ calculating solutions...

:: The following 1 package(s) are getting updated:
   aur/coursier  1.1.0_M4-1            ->  1.1.0_M7-1

?? Do you want to continue? Y/n: 
~~ looking for new pkgbuilds and fetching them...
==> Making package: coursier 1.1.0_M7-1 (Thu 30 Aug 2018 16:34:04 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found coursier
==> Validating source files with sha256sums...
    coursier ... FAILED
==> ERROR: One or more files did not pass the validity check!
2018-08-30 16:34:04,738 - wrappers - makepkg - ERROR - makepkg query ['makepkg', '-cf', '--noconfirm'] failed in directory /home/jk/.cache/aurman/coursier
```
To me, this looks like a mismatch of the sha256 in the PKGBUILD and the one obtained from source. If I can take steps to resolve the issue on my end, please let me know.

**Comment by 2m** [comment]
I tried removing and installing coursier again with `yay` and it installed without any problems. Do you still have the same problem when trying to install it?

**Comment by 2m** [comment]
I think this could have been caused by the fact, that coursier binary has the same file name across different versions. Therefore when there was an update, aurman saw that the file with that name already existed and did not re-download it. And then the checksum failed.

If that happens again, try removing aurman cache for the coursier package.

Please let me know if someone knows how to fix it in the PKGBUILD.
